### ISSUE TITLE
Windows & Linux VM OS update patching

### ISSUE THREAD

**Issue by jonnyry** [nwsde/nwsde-azuretre#13]
https://github.com/microsoft/AzureTRE/issues/3788

**Comment by vvcb** [comment]
1. We need to understand why we need to patch OS in isolated networks.
2. Related to this will be the ability to have a marketplace of customised VM images
3. Customised VM images can have licensed software - where licenses are either paid for by research team or provided as license keys/files by the research team
4. Some licensing may require access to internet - test case would be Matlab

**Comment by jonnyry** [comment]
Resolved in

https://github.com/nwsde/nwsde-azuretre/issues/75
https://github.com/nwsde/nwsde-azuretre/issues/76
